spring:
  application:
    name: coupon-fcfs
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: scheduler-WithoutLua

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_insert: true
  data:
    redis:
      host: localhost
      port: 6379